name: 'GitHub Action for GraalVM'
description: 'Set up a specific version of GraalVM Community Edition (CE) or Enterprise Edition (EE)'
author: 'GraalVM Community'
branding:
  icon: 'terminal'  
  color: 'blue'
inputs:
  version:
    required: true
    description: 'GraalVM version (release, latest, dev).'
  gds-token:
    required: false
    description: 'Download token for the GraalVM Download Service. If provided, the action will set up GraalVM Enterprise Edition.'
  java-version:
    required: true
    description: 'Java version (11 or 17, 8 or 16 for older releases).'
  components:
    required: false
    description: 'Comma-separated list of GraalVM components to be installed.'
    default: ''
  github-token:
    required: false
    description: 'Set it to secrets.GITHUB_TOKEN to increase rate limits when accessing the GitHub API.'
    default: ''
  set-java-home:
    required: false
    description: 'Set $JAVA_HOME to the GraalVM installation. Default: true.'
    default: 'true'
  cache:
    description: 'Name of the build platform to cache dependencies. It can be "maven", "gradle", or "sbt".'
    required: false
  native-image-musl:
    required: false
    description: 'Set up musl for static image building with GraalVM Native Image.'
    default: 'false'
  native-image-report-build:
    required: false
    description: 'Generate report of Native-Image build.'
    default: 'false'
  native-image-report-artifact:
    required: false
    description: 'Generate report of Native-Image artifact.'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
  post-if: 'success()'
